language: python

dist: trusty

notifications:
    email: false

matrix:
    include:
        - env: LINT_CHECK
          python: "3.6"
          install: pip install flake8
          script: flake8 --exclude migrations,scripts
